name: Build debug APK

on:
  push:
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build debug APKs
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Build debug APKs
        run: ./gradlew assembleAll
      - name: Upload debug froid APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-fdroid-debug.apk
          path: app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk
          retention-days: 1
      - name: Upload debug full APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-full-debug.apk
          path: app/build/outputs/apk/full/debug/app-full-debug.apk
          retention-days: 1
