name: Build release APKs

on:
  push:
    tags:
      - '*'

jobs:
  build:
    permissions:
      contents: write
    name: Build release APKs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Gradle build action
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Get version name
        id: get-version
        run: echo "VERSION_NAME=$(./gradlew -q printVersionName)" >> $GITHUB_OUTPUT
      - name: Verify version name equals git tag
        if: ${{ github.ref_name != steps.get-version.outputs.VERSION_NAME }}
        run: exit 1
      - name: Decode Keystore
        run: echo "${{ secrets.SIGNING_KEY_STORE_BASE64 }}" | base64 -d - > keystore.jks
      - name: Build fdroid release APK
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew :app:assembleFdroidRelease
      - name: Build full release APK
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew -PenableAbiSplit :app:assembleFullRelease
      - name: Upload APKs as assets to the GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build/outputs/apk/fdroid/release/app-fdroid-release.apk
            app/build/outputs/apk/full/release/app-full-universal-release.apk
            app/build/outputs/apk/full/release/app-full-armeabi-v7a-release.apk
            app/build/outputs/apk/full/release/app-full-arm64-v8a-release.apk
            app/build/outputs/apk/full/release/app-full-x86-release.apk
            app/build/outputs/apk/full/release/app-full-x86_64-release.apk
      # Build APK set for Accrescent
      - name: Build release APK set
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew :app:buildApksFullRelease
      - name: Upload release APK set as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-fullRelease.apks
          path: app/build/outputs/apkset/fullRelease/app-fullRelease.apks
          retention-days: 7
